/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-03-07 09:48:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.tapfoods.model.User;
import java.util.List;
import com.tapfoods.model.Menu;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1740980311695L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.tapfoods.model.User");
    _jspx_imports_classes.add("com.tapfoods.model.Menu");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

/**
 * <p>This code block retrieves the user object from the session. If the user is not authenticated or their email is not set, 
 * it redirects the user to the sign-in page.</p>
 * 
 * <p>The check ensures that the user is logged in and has a valid email address before allowing access to the current page. 
 * If the user is not authenticated, they are redirected to the sign-in page to log in.</p>
 * 
 * <p>The cache control headers are set to prevent caching of the redirection page. This ensures that the browser or any 
 * intermediary caches do not store the redirected page and always fetches the latest version when the user is redirected 
 * to the sign-in page.</p>
 */
User user = (User) session.getAttribute("user");
/**	
 	if (user == null || user.getEmail() == null || user.getEmail().isEmpty()) {
	// Ensure proper cache control for redirected pages
	response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); // HTTP 1.1
	response.setHeader("Pragma", "no-cache"); // HTTP 1.0
	response.setDateHeader("Expires", 0); // Proxies
	// Redirect to sign-in page
	response.sendRedirect("signIn.jsp");
	// Ensure no further content is processed
	return;
}
*/

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"icon\" href=\"admin/styles/images/favicon.png\" type=\"image/png\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("<p>This section includes the necessary stylesheets and external resources required for the page.</p>\r\n");
      out.write("\r\n");
      out.write("<p>The Bootstrap CSS file is included for responsive design and component styling. The Font Awesome CSS file \r\n");
      out.write("provides icons used throughout the site. Additionally, custom stylesheets are linked to handle layout, component, \r\n");
      out.write("and form-specific styles.</p>\r\n");
      out.write("\r\n");
      out.write("<ul>\r\n");
      out.write("  <li><code>https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css</code>: Includes Bootstrap 5.0.2 for styling \r\n");
      out.write("  and responsive design.</li>\r\n");
      out.write("  <li><code>https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css</code>: Includes Font Awesome icons.</li>\r\n");
      out.write("  <li><code>styles/layouts.css</code>: Custom stylesheet for layout styling.</li>\r\n");
      out.write("  <li><code>styles/components.css</code>: Custom stylesheet for component-specific styling.</li>\r\n");
      out.write("  <li><code>styles/forms-profile.css</code>: Custom stylesheet for form and profile-related styles.</li>\r\n");
      out.write("</ul>\r\n");
      out.write("-->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"admin/styles/layouts.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"admin/styles/components.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"admin/styles/forms-profile.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".filter-tag {\r\n");
      out.write("	display: inline-flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	padding: 0.3rem .5rem;\r\n");
      out.write("	margin: 0.25rem;\r\n");
      out.write("	background-color: #e9ecef;\r\n");
      out.write("	font-size: 0.875rem;\r\n");
      out.write("	color: #495057;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!--\r\n");
      out.write("    <p>This section defines the navigation bar for the website. The navbar is fixed at the top and uses Bootstrap's \r\n");
      out.write("    responsive design classes for layout and styling.</p>\r\n");
      out.write("\r\n");
      out.write("    <p>The navbar includes the following components:</p>\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li><strong>Branding:</strong> Displays the site logo and name (\"RoyalKitchen\"). The logo image is included using \r\n");
      out.write("        an <code>&lt;img&gt;</code> tag.</li>\r\n");
      out.write("        <li><strong>Toggler Button:</strong> A button that toggles the collapse of the navbar on smaller screens. It uses \r\n");
      out.write("        the Font Awesome bars icon for representation.</li>\r\n");
      out.write("        <li><strong>Search Dropdown:</strong> A dropdown menu that contains a search form with an input field and a search \r\n");
      out.write("        button.</li>\r\n");
      out.write("        <li><strong>Profile Dropdown:</strong> A dropdown menu that provides options for profile management, including \r\n");
      out.write("        viewing profile details, updating the profile, and deleting the profile. Each option opens a corresponding modal.</li>\r\n");
      out.write("        <li><strong>Additional Links:</strong> Links to offers, reviews, help, and cart.</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    -->\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light bg-light fixed-top\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<a class=\"navbar-brand ms-4 ms-md-0\" href=\"index.jsp\"> <img\r\n");
      out.write("				src=\"admin/styles/images/logo.png\" alt=\"\" width=\"30\" height=\"28\"\r\n");
      out.write("				class=\"d-inline-block align-text-top\"> RoyalKitchen\r\n");
      out.write("			</a>\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("				data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("				aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<i class=\"fas fa-bars\"></i>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"collapse navbar-collapse mt-3 mt-lg-0\"\r\n");
      out.write("				id=\"navbarSupportedContent\">\r\n");
      out.write("				<ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("					<li class=\"nav-item dropdown\"><a\r\n");
      out.write("						class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("							Search </a>\r\n");
      out.write("						<ul class=\"dropdown-menu dropdown-menu-center mt-lg-4\"\r\n");
      out.write("							aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("							<li style=\"border: solid 1px red;\">\r\n");
      out.write("								<form class=\"d-flex p-2\" action=\"globalSearch\" method=\"post\"\r\n");
      out.write("									id=\"searchForm\">\r\n");
      out.write("									<input class=\"form-control me-2\" type=\"search\" name=\"query\"\r\n");
      out.write("										id=\"searchInput\" placeholder=\"Search by name or cuisine\"\r\n");
      out.write("										aria-label=\"Search\" style=\"border: none; outline: none;\">\r\n");
      out.write("									<button class=\"btn outline-primary\" type=\"submit\">\r\n");
      out.write("										<i class=\"fas fa-search\"></i>\r\n");
      out.write("									</button>\r\n");
      out.write("								</form>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li class=\"mt-1\" style=\"border: solid 1px red;\">\r\n");
      out.write("								<div class=\"p-3 d-flex flex-wrap justify-content-center\">\r\n");
      out.write("									<button class=\"btn flex-grow-1 search me-2 mb-2\"\r\n");
      out.write("										onclick=\"setSearchValue('sweet')\">Sweet</button>\r\n");
      out.write("									<button class=\"btn flex-grow-1 search me-2 mb-2\"\r\n");
      out.write("										onclick=\"setSearchValue('ice cream')\">Ice Cream</button>\r\n");
      out.write("									<button class=\"btn flex-grow-1 search mb-2\"\r\n");
      out.write("										onclick=\"setSearchValue('spice')\">Spice</button>\r\n");
      out.write("									<button class=\"btn flex-grow-1 search me-2 mb-2\"\r\n");
      out.write("										onclick=\"setSearchValue('biryani')\">Biryani</button>\r\n");
      out.write("									<button class=\"btn flex-grow-1 search me-2 mb-2\"\r\n");
      out.write("										onclick=\"setSearchValue('meat')\">Meat</button>\r\n");
      out.write("									<button class=\"btn flex-grow-1 search mb-2\"\r\n");
      out.write("										onclick=\"setSearchValue('chicken')\">Chicken</button>\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("\r\n");
      out.write("					");

					if (user == null) {
					
      out.write("\r\n");
      out.write("					<li class=\"nav-item dropdown\"><a\r\n");
      out.write("						class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("							Auth </a>\r\n");
      out.write("						<ul class=\"dropdown-menu dropdown-menu-center custom-menu mt-lg-4\"\r\n");
      out.write("							aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"#\" data-bs-toggle=\"modal\"\r\n");
      out.write("								data-bs-target=\"#adminModal\" id=\"adminLogin\">Admin</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"signIn.jsp\"\r\n");
      out.write("								id=\"userLogin\">User</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					");

					}
					if (user != null) {
					
      out.write("\r\n");
      out.write("					<li class=\"nav-item dropdown\"><a\r\n");
      out.write("						class=\"nav-link dropdown-toggle\" href=\"#\" id=\"profileDropdown\"\r\n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"true\">\r\n");
      out.write("							Profile </a>\r\n");
      out.write("						<ul class=\"dropdown-menu dropdown-menu-center custom-menu mt-lg-4\"\r\n");
      out.write("							aria-labelledby=\"profileDropdown\">\r\n");
      out.write("							<li class=\"dropdown-item\" id=\"profileDetails\"\r\n");
      out.write("								data-bs-toggle=\"modal\" data-bs-target=\"#profileModal\">Profile\r\n");
      out.write("								Details</li>\r\n");
      out.write("							<li class=\"dropdown-item\" id=\"updateProfile\"\r\n");
      out.write("								data-bs-toggle=\"modal\" data-bs-target=\"#updateModal\">Update\r\n");
      out.write("								Profile</li>\r\n");
      out.write("							<li class=\"dropdown-item\" id=\"deleteProfile\"\r\n");
      out.write("								data-bs-toggle=\"modal\" data-bs-target=\"#deleteModal\">Delete\r\n");
      out.write("								Profile</li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"searchRestaurants\">Home</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"help.jsp\">Help</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"OrderHistory\">History</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"cart.jsp\">Cart</a></li>\r\n");
      out.write("					");

					if (user == null) {
					
      out.write("\r\n");
      out.write("					<li class=\"nav-item\"><a\r\n");
      out.write("						class=\"nav-link btn btn-outline-danger\" href=\"signIn.jsp\"\r\n");
      out.write("						style=\"padding: 5px; color: #dc3545; background-color: transparent;\"\r\n");
      out.write("						onmouseover=\"this.style.setProperty('color', '#fff', 'important'); this.style.setProperty('background-color', '#dc3545', 'important');\"\r\n");
      out.write("						onmouseout=\"this.style.setProperty('color', '#dc3545', 'important'); this.style.setProperty('background-color', 'transparent', 'important');\">\r\n");
      out.write("							Sign In </a></li>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("	<!-- \r\n");
      out.write("		<p>Modal for administrator access, including a form for entering a private key.</p>\r\n");
      out.write("	-->\r\n");
      out.write("	<div class=\"modal fade\" id=\"adminModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"adminModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"adminModalLabel\">Administrator\r\n");
      out.write("						Access</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"\r\n");
      out.write("						style=\"background-color: transparent; border: none;\"\r\n");
      out.write("						onmouseover=\"this.style.backgroundColor='lightcoral';\"\r\n");
      out.write("						onmouseout=\"this.style.backgroundColor='transparent';\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<form action=\"AdminAccessServlet\" method=\"post\">\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"privateKey\" class=\"form-label\">Enter\r\n");
      out.write("								Administrator Private Key</label>\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"password\" class=\"form-control\" id=\"privateKey\"\r\n");
      out.write("									name=\"privateKey\" required style=\"border: solid 1px lightgray;\">\r\n");
      out.write("								<div class=\"input-group-append\">\r\n");
      out.write("									<span class=\"input-group-text\" id=\"toggle-privateKey\"\r\n");
      out.write("										data-toggle=\"password\" data-target=\"privateKey\"\r\n");
      out.write("										style=\"cursor: pointer;\"> <i class=\"fas fa-eye\"></i>\r\n");
      out.write("									</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<small class=\"info-message mt-3\"\r\n");
      out.write("							style=\"color: red; font-size: 13px;\"> ** This field will\r\n");
      out.write("							redirect you to the admin sign-in page. Make sure to enter the\r\n");
      out.write("							correct password. If you don't know it, please contact the\r\n");
      out.write("							administrator. ** </small>\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-success\"\r\n");
      out.write("							style=\"margin-left: auto; display: flex;\">Submit</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Profile Modal -->\r\n");
      out.write("	<div class=\"modal fade show\" id=\"profileModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"profileModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"profileModalLabel\">Profile Details</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"\r\n");
      out.write("						style=\"background-color: transparent; border: none;\"\r\n");
      out.write("						onmouseover=\"this.style.backgroundColor='lightcoral';\"\r\n");
      out.write("						onmouseout=\"this.style.backgroundColor='transparent';\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body custom-scroll\">\r\n");
      out.write("					<table class=\"table table-striped\">\r\n");
      out.write("						<thead>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>Field</th>\r\n");
      out.write("								<th>Value</th>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("						<tbody>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>User ID</td>\r\n");
      out.write("								<td><input type=\"text\" id=\"profileUserId\"\r\n");
      out.write("									value=\"");
      out.print(user != null ? user.getUserid() : "");
      out.write("\"\r\n");
      out.write("									class=\"form-control field-editable\" disabled\r\n");
      out.write("									style=\"border: 1px solid lightgray;\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>Email</td>\r\n");
      out.write("								<td><input type=\"text\" id=\"profileEmail\"\r\n");
      out.write("									value=\"");
      out.print(user != null ? user.getEmail() : "");
      out.write("\"\r\n");
      out.write("									class=\"form-control field-editable\" disabled\r\n");
      out.write("									style=\"border: 1px solid lightgray;\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>Username</td>\r\n");
      out.write("								<td><input type=\"text\" id=\"profileUsername\"\r\n");
      out.write("									value=\"");
      out.print(user != null ? user.getUsername() : "");
      out.write("\"\r\n");
      out.write("									class=\"form-control field-editable\" disabled\r\n");
      out.write("									style=\"border: 1px solid lightgray;\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>Phone Number</td>\r\n");
      out.write("								<td><input type=\"text\" id=\"profilePhoneNumber\"\r\n");
      out.write("									value=\"");
      out.print(user != null ? user.getPhonenumber() : "");
      out.write("\"\r\n");
      out.write("									class=\"form-control field-editable\" disabled\r\n");
      out.write("									style=\"border: 1px solid lightgray;\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>Address</td>\r\n");
      out.write("								<td><input type=\"text\" id=\"profileAddress\"\r\n");
      out.write("									value=\"");
      out.print(user != null ? user.getAddress() : "");
      out.write("\"\r\n");
      out.write("									class=\"form-control field-editable\" disabled\r\n");
      out.write("									style=\"border: 1px solid lightgray;\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>Password</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<div class=\"input-group\">\r\n");
      out.write("										<input type=\"password\" id=\"profilePassword\"\r\n");
      out.write("											value=\"");
      out.print(user != null ? user.getPassword() : "");
      out.write("\"\r\n");
      out.write("											class=\"form-control field-editable\" disabled\r\n");
      out.write("											style=\"border: 1px solid lightgray;\">\r\n");
      out.write("										<div class=\"input-group-append\" style=\"border-radius: 10px;\">\r\n");
      out.write("											<span class=\"input-group-text\" id=\"toggle-profile-password\"\r\n");
      out.write("												data-toggle=\"password\" data-target=\"profilePassword\"\r\n");
      out.write("												style=\"height: 38px; line-height: 38px; cursor: pointer;\">\r\n");
      out.write("												<i class=\"fas fa-eye\" id=\"profilePasswordEye\"></i>\r\n");
      out.write("											</span>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("					<form action=\"navbar.jsp\" method=\"post\" style=\"display: inline;\">\r\n");
      out.write("						<input type=\"hidden\" name=\"logout\" value=\"true\">\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-warning\">\r\n");
      out.write("							Logout <i class=\"fas fa-arrow-right\" style=\"font-size: 13px;\"></i>\r\n");
      out.write("						</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-danger\"\r\n");
      out.write("						data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");

	/**
	 * This section handles the logout process and controls caching behavior.
	 *
	 * <p>Logout Handling:</p>
	 * <p>This block of code checks if the current request is a POST request and if the `logout` parameter is set to "true". 
	 * If both conditions are met, it performs the following actions:</p>
	 * <ul>
	 *   <li><code>session.invalidate();</code> - Invalidates the current user session, logging the user out by removing 
	 *   all session attributes.</li>
	 *   <li><code>response.sendRedirect("signIn.jsp");</code> - Redirects the user to the sign-in page so they can log in 
	 *   again.</li>
	 * </ul>
	 *
	 * <p>Cache Control Headers:</p>
	 * <p>This part of the code sets HTTP headers to control caching behavior for the response:</p>
	 * <ul>
	 *   <li><code>response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");</code> - This HTTP 1.1 header 
	 *   instructs the browser and any intermediate caches to not cache the response. It ensures that the page is always fetched 
	 *   fresh from the server.</li>
	 *   <li><code>response.setHeader("Pragma", "no-cache");</code> - This HTTP 1.0 header provides backward compatibility 
	 *   with older HTTP standards, ensuring that the response is not cached.</li>
	 *   <li><code>response.setDateHeader("Expires", 0);</code> - This header is used to specify that the response has already 
	 *   expired, which prevents caching by proxies.</li>
	 * </ul>
	 */
	if ("POST".equalsIgnoreCase(request.getMethod()) && "true".equals(request.getParameter("logout"))) {
		session.invalidate();
		response.sendRedirect("searchRestaurants");
	}
	response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); // HTTP 1.1
	response.setHeader("Pragma", "no-cache"); // HTTP 1.0
	response.setDateHeader("Expires", 0); // Proxies
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--\r\n");
      out.write("<p>This section defines the Update Profile modal window, which allows users to update their profile details.</p>\r\n");
      out.write("\r\n");
      out.write("<p>The modal is designed with the following components:</p>\r\n");
      out.write("<ul>\r\n");
      out.write("  <li><strong>Modal Header:</strong> Displays the title \"Update Profile\" and a close button.</li>\r\n");
      out.write("  <li><strong>Modal Body:</strong> Contains a form with a table displaying the profile fields and editable options.</li>\r\n");
      out.write("  <li><strong>Modal Footer:</strong> Provides a button to close the modal.</li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<p><strong>Modal Body Form:</strong> The form allows users to update their profile details. It includes the following fields:</p>\r\n");
      out.write("<ul>\r\n");
      out.write("  <li><strong>Email:</strong> Displays the email address as read-only with a \"Cannot Edit\" button.</li>\r\n");
      out.write("  <li><strong>Username:</strong> Shows the username with an \"Edit\" button to enable editing.</li>\r\n");
      out.write("  <li><strong>Phone Number:</strong> Displays the phone number with an \"Edit\" button to enable editing.</li>\r\n");
      out.write("  <li><strong>Address:</strong> Shows the address with an \"Edit\" button to enable editing.</li>\r\n");
      out.write("  <li><strong>Password:</strong> Displays the password with an \"Edit\" button to enable editing.</li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<p>The buttons for editing fields are initially disabled and will enable the corresponding fields for editing when clicked. The \"Update\" button submits the form to save changes.</p>\r\n");
      out.write("\r\n");
      out.write("<p><strong>Note:</strong> This modal uses Bootstrap classes for styling and responsiveness, and Font Awesome icons for visual elements.</p>\r\n");
      out.write("-->\r\n");
      out.write("	<!-- Update Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"updateModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"updateModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"updateModalLabel\">Update Profile</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"\r\n");
      out.write("						style=\"background-color: transparent; border: none;\"\r\n");
      out.write("						onmouseover=\"this.style.backgroundColor='lightcoral';\"\r\n");
      out.write("						onmouseout=\"this.style.backgroundColor='transparent';\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body custom-scroll\">\r\n");
      out.write("					<form action=\"updateProfile\" method=\"post\">\r\n");
      out.write("						<table class=\"table table-striped\">\r\n");
      out.write("							<thead>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th>Field</th>\r\n");
      out.write("									<th>Value</th>\r\n");
      out.write("									<th class=\"text-center\">Actions</th>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</thead>\r\n");
      out.write("							<tbody>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>Email</td>\r\n");
      out.write("									<td><input type=\"email\" id=\"emailField\" name=\"email\"\r\n");
      out.write("										value=\"");
      out.print(user != null ? user.getEmail() : "");
      out.write("\"\r\n");
      out.write("										class=\"form-control field-editable\" readonly disabled\r\n");
      out.write("										style=\"border: 1px solid lightgray;\"></td>\r\n");
      out.write("									<td class=\"text-center\">\r\n");
      out.write("										<button type=\"button\" class=\"btn btn-secondary btn-sm\"\r\n");
      out.write("											disabled\r\n");
      out.write("											style=\"height: 33px; width: 33px; border-radius: 4px; border: none; border-radius: 20px;\">\r\n");
      out.write("											<i class=\"fas fa-lock\"></i>\r\n");
      out.write("										</button>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>Username</td>\r\n");
      out.write("									<td><input type=\"text\" id=\"usernameField\" name=\"username\"\r\n");
      out.write("										value=\"");
      out.print(user != null ? user.getUsername() : "");
      out.write("\"\r\n");
      out.write("										class=\"form-control field-editable\" disabled\r\n");
      out.write("										style=\"border: 1px solid lightgray;\"></td>\r\n");
      out.write("									<td class=\"text-center\">\r\n");
      out.write("										<button type=\"button\" id=\"editUsernameBtn\"\r\n");
      out.write("											class=\"btn btn-warning btn-sm\"\r\n");
      out.write("											style=\"height: 33px; width: 33px; border-radius: 4px; border: none; border-radius: 20px;\">\r\n");
      out.write("											<i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("										</button>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>Phone Number</td>\r\n");
      out.write("									<td><input type=\"text\" id=\"phoneNumberField\"\r\n");
      out.write("										name=\"phonenumber\"\r\n");
      out.write("										value=\"");
      out.print(user != null ? user.getPhonenumber() : "");
      out.write("\"\r\n");
      out.write("										class=\"form-control field-editable\" disabled\r\n");
      out.write("										style=\"border: 1px solid lightgray;\"></td>\r\n");
      out.write("									<td class=\"text-center\">\r\n");
      out.write("										<button type=\"button\" id=\"editPhoneNumberBtn\"\r\n");
      out.write("											class=\"btn btn-warning btn-sm\"\r\n");
      out.write("											style=\"height: 33px; width: 33px; border-radius: 4px; border: none; border-radius: 20px;\">\r\n");
      out.write("											<i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("										</button>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>Address</td>\r\n");
      out.write("									<td><input type=\"text\" id=\"addressField\" name=\"address\"\r\n");
      out.write("										value=\"");
      out.print(user != null ? user.getAddress() : "");
      out.write("\"\r\n");
      out.write("										class=\"form-control field-editable\" disabled\r\n");
      out.write("										style=\"border: 1px solid lightgray;\"></td>\r\n");
      out.write("									<td class=\"text-center\">\r\n");
      out.write("										<button type=\"button\" id=\"editAddressBtn\"\r\n");
      out.write("											class=\"btn btn-warning btn-sm\"\r\n");
      out.write("											style=\"height: 33px; width: 33px; border-radius: 4px; border: none; border-radius: 20px;\">\r\n");
      out.write("											<i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("										</button>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>Password</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<div class=\"input-group\">\r\n");
      out.write("											<input type=\"password\" id=\"passwordField\" name=\"password\"\r\n");
      out.write("												value=\"");
      out.print(user != null ? user.getPassword() : "");
      out.write("\"\r\n");
      out.write("												class=\"form-control field-editable\" disabled\r\n");
      out.write("												style=\"border: 1px solid lightgray;\">\r\n");
      out.write("											<div class=\"input-group-append\" style=\"border-radius: 10px;\">\r\n");
      out.write("												<span class=\"input-group-text\" id=\"toggle-password-field\"\r\n");
      out.write("													data-toggle=\"password\" data-target=\"passwordField\"\r\n");
      out.write("													style=\"height: 38px; line-height: 38px; background-color: white; cursor: pointer;\">\r\n");
      out.write("													<i class=\"fas fa-eye\"></i>\r\n");
      out.write("												</span>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td class=\"text-center\">\r\n");
      out.write("										<button type=\"button\" id=\"editPasswordBtn\"\r\n");
      out.write("											class=\"btn btn-warning btn-sm\"\r\n");
      out.write("											style=\"height: 33px; width: 33px; border-radius: 4px; border: none; border-radius: 20px;\">\r\n");
      out.write("											<i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("										</button>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-success\" id=\"saveChanges\">\r\n");
      out.write("							Update <i class=\"fas fa-cloud-upload-alt\"></i>\r\n");
      out.write("						</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-danger\"\r\n");
      out.write("						data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!--\r\n");
      out.write("<p>This section includes two modal dialogs for profile deletion:</p>\r\n");
      out.write("\r\n");
      out.write("<ul>\r\n");
      out.write("  <li><strong>Delete Modal:</strong> Prompts the user to confirm their intention to delete their profile.</li>\r\n");
      out.write("  <li><strong>Confirmation Modal:</strong> Requests confirmation from the user by asking for their email and password before proceeding with the deletion.</li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<p><strong>Delete Modal:</strong> This modal is displayed first when the user initiates a profile deletion request.</p>\r\n");
      out.write("<ul>\r\n");
      out.write("  <li><strong>Modal Header:</strong> Displays the title \"Delete Profile\" and a close button.</li>\r\n");
      out.write("  <li><strong>Modal Body:</strong> Contains a confirmation message asking if the user is sure they want to delete their profile.</li>\r\n");
      out.write("  <li><strong>Modal Footer:</strong> Includes \"Cancel\" and \"Yes, Delete Profile\" buttons. Clicking \"Yes, Delete Profile\" opens the Confirmation Modal, while \"Cancel\" closes the modal.</li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<p><strong>Confirmation Modal:</strong> This modal is displayed after the user clicks \"Yes, Delete Profile\" in the Delete Modal.</p>\r\n");
      out.write("<ul>\r\n");
      out.write("  <li><strong>Modal Header:</strong> Displays the title \"Confirm Delete Profile\" and a close button.</li>\r\n");
      out.write("  <li><strong>Modal Body:</strong> Contains a form that requires the user to enter their email and password to confirm the deletion. The email field is pre-filled and read-only, while the password field is required for confirmation.</li>\r\n");
      out.write("  <li><strong>Modal Footer:</strong> Includes \"Cancel\" and \"Confirm Delete\" buttons. Clicking \"Confirm Delete\" submits the form to delete the profile, while \"Cancel\" closes the modal.</li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<p><strong>Note:</strong> Both modals use Bootstrap classes for styling and responsiveness, and Font Awesome icons for visual elements.</p>\r\n");
      out.write("-->\r\n");
      out.write("	<!-- Delete Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"deleteModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"deleteModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"deleteModalLabel\">Delete Profile</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"\r\n");
      out.write("						style=\"background-color: transparent; border: none;\"\r\n");
      out.write("						onmouseover=\"this.style.backgroundColor='lightcoral';\"\r\n");
      out.write("						onmouseout=\"this.style.backgroundColor='transparent';\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<p>Are you sure you want to delete your profile?</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-danger\" data-bs-toggle=\"modal\"\r\n");
      out.write("						data-bs-target=\"#confirmDeleteModal\">Yes, Delete Profile</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Confirmation Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"confirmDeleteModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"confirmDeleteModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"confirmDeleteModalLabel\">Confirm\r\n");
      out.write("						Delete Profile</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"\r\n");
      out.write("						style=\"background-color: transparent; border: none;\"\r\n");
      out.write("						onmouseover=\"this.style.backgroundColor='lightcoral';\"\r\n");
      out.write("						onmouseout=\"this.style.backgroundColor='transparent';\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<form action=\"deleteProfile\" method=\"post\">\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"email\" class=\"form-label\">Email</label> <input\r\n");
      out.write("								type=\"email\" class=\"form-control\" id=\"email\" name=\"email\"\r\n");
      out.write("								required\r\n");
      out.write("								style=\"border: 1px solid lightgray; background-color: lightcoral;\"\r\n");
      out.write("								value=\"");
      out.print(user != null ? user.getEmail() : "");
      out.write("\" readonly>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"password\" class=\"form-label\">Password</label>\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"password\" class=\"form-control\" id=\"password\"\r\n");
      out.write("									name=\"password\" required style=\"border: 1px solid lightgray;\">\r\n");
      out.write("								<div class=\"input-group-append\">\r\n");
      out.write("									<span class=\"input-group-text\" id=\"toggle-password\"\r\n");
      out.write("										data-toggle=\"password\" data-target=\"password\"\r\n");
      out.write("										style=\"cursor: pointer;\"> <i class=\"fas fa-eye\"></i>\r\n");
      out.write("									</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-danger\">\r\n");
      out.write("							Delete <i class=\"fas fa-trash-alt\"></i>\r\n");
      out.write("						</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Include external JavaScript files for functionality and interactivity -->\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\" src=\"admin/styles/password.js\"></script>\r\n");
      out.write("	<!-- Link to the local JavaScript file for profile-specific functionality -->\r\n");
      out.write("	<script type=\"text/javascript\" src=\"profile.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Include jQuery slim version from CDN (Content Delivery Network) -->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Include Popper.js for handling popovers and tooltips -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Include Bootstrap 5.0.2 JavaScript for Bootstrap components -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://stackpath.bootstrapcdn.com/bootstrap/5.0.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Include Bootstrap 5.0.2 JavaScript bundle with Popper.js integrated -->\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		function setSearchValue(query) {\r\n");
      out.write("			document.getElementById('searchInput').value = query;\r\n");
      out.write("			document.getElementById('searchForm').submit();\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Integer restaurantId = (Integer) session.getAttribute("restaurantId");
String restaurantName = (String)session.getAttribute("restaurantName");
if (restaurantId == null) {
	restaurantId = 0; // Default value if not set
}
List<Menu> menuItems = (List<Menu>) session.getAttribute("menuList");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>");
      out.print(restaurantName!=null?restaurantName : "MenuItems" );
      out.write("</title>\r\n");
      out.write(" <link rel=\"icon\" href=\"admin/styles/images/favicon.png\" type=\"image/png\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/5.0.2/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"admin/styles/restaurant.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"admin/styles/menuItem.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container mt-5 py-5\">\r\n");
      out.write("		<a href=\"searchRestaurants\" class=\"text-danger\">>>Back</a>\r\n");
      out.write("\r\n");
      out.write("		<!-- Display active filters -->\r\n");
      out.write("		<div class=\"mb-4 mt-3\">\r\n");
      out.write("			");

			List<String> activeQueries = (List<String>) session.getAttribute("activeQueries");
			// Retrieve the restaurantId from session
			if (activeQueries != null && !activeQueries.isEmpty()) {
			
      out.write("\r\n");
      out.write("			<div class=\"filter-tags\">\r\n");
      out.write("				");

				for (String q : activeQueries) {
				
      out.write("\r\n");
      out.write("				<div class=\"filter-tag\">\r\n");
      out.write("					<span>");
      out.print(q);
      out.write("</span>\r\n");
      out.write("					<form action=\"searchMenu\" method=\"post\" style=\"display: inline;\">\r\n");
      out.write("						<!-- Assuming restaurantId needs to be dynamically retrieved from menuItems -->\r\n");
      out.write("						<input type=\"hidden\" name=\"restaurantId\" value=\"");
      out.print(restaurantId);
      out.write("\">\r\n");
      out.write("						<input type=\"hidden\" name=\"removeQuery\" value=\"");
      out.print(q);
      out.write("\">\r\n");
      out.write("						<button type=\"submit\" class=\"btn-close\" aria-label=\"Close\"></button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Default cuisine filters with option to add -->\r\n");
      out.write("		<div class=\"mb-4\">\r\n");
      out.write("			<p class=\"text-danger\">Explore Trending Flavors</p>\r\n");
      out.write("			<div class=\"default-filters\">\r\n");
      out.write("				");

				List<String> cuisineFilters = List.of("Available", "< Rs.150", "Rs.150-250", "Rs.250-350", "> Rs.350");
				for (String filter : cuisineFilters) {
				
      out.write("\r\n");
      out.write("				<div class=\"filter-tag\">\r\n");
      out.write("					<form action=\"searchMenu\" method=\"post\" style=\"display: inline;\">\r\n");
      out.write("						<!-- Assuming restaurantId needs to be dynamically retrieved from menuItems -->\r\n");
      out.write("						<input type=\"hidden\" name=\"restaurantId\" value=\"");
      out.print(restaurantId);
      out.write("\">\r\n");
      out.write("						<input type=\"hidden\" name=\"addQuery\" value=\"");
      out.print(filter);
      out.write("\">\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-sm\">\r\n");
      out.write("							<span>");
      out.print(filter);
      out.write("</span> +\r\n");
      out.write("						</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Display list of menu items as Bootstrap cards -->\r\n");
      out.write("		<div class=\"row mt-2\">\r\n");
      out.write("			");

			if (menuItems != null && !menuItems.isEmpty()) {
				for (Menu item : menuItems) {
					Integer itemRestaurantId = item.getRestaurantid(); // Get restaurantId from each Menu item
					boolean isAvailable = "Available".equalsIgnoreCase(item.getIsavailable()); // Check availability
					String cardClass = isAvailable ? "" : "card-inactive";
					String labelClass = isAvailable ? "d-none" : ""; // Show label if unavailable
					String clickClass = isAvailable ? "" : "click-disabled"; // Disable click if unavailable
			
      out.write("\r\n");
      out.write("			<div class=\"col-md-3 mb-4\">\r\n");
      out.write("				<form action=\"menuDetails\" method=\"post\">\r\n");
      out.write("					<input type=\"hidden\" name=\"restaurantId\"\r\n");
      out.write("						value=\"");
      out.print(itemRestaurantId);
      out.write("\"> <input type=\"hidden\"\r\n");
      out.write("						name=\"id\" value=\"");
      out.print(item.getMenuid());
      out.write("\">\r\n");
      out.write("						<input type=\"hidden\"\r\n");
      out.write("						name=\"menuName\" value=\"");
      out.print(item.getMenuname());
      out.write("\">\r\n");
      out.write("					<div class=\"card ");
      out.print(cardClass);
      out.write(' ');
      out.print(clickClass);
      out.write("\"\r\n");
      out.write("						style=\"height: 270px; display: flex; flex-direction: column; overflow: hidden; cursor: pointer;\"\r\n");
      out.write("						onclick=\"this.closest('form').submit();\">\r\n");
      out.write("						<!-- Not Available label -->\r\n");
      out.write("						<div class=\"position-relative\">\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"badge bg-danger text-light position-absolute d-flex top-0 start-0 m-2 ");
      out.print(labelClass);
      out.write("\"\r\n");
      out.write("								style=\"font-size: 0.875rem;\">Not Available</div>\r\n");
      out.write("\r\n");
      out.write("							<!-- Image at the top of the card -->\r\n");
      out.write("							<img\r\n");
      out.write("								src=\"admin/styles/images/");
      out.print(item.getImagepath() != null ? item.getImagepath() : "defaultImg.png");
      out.write("\"\r\n");
      out.write("								class=\"card-img-top\" alt=\"");
      out.print(item.getMenuname());
      out.write("\"\r\n");
      out.write("								style=\"min-height: 150px; height: 150px; object-fit: cover; width: 100%;\">\r\n");
      out.write("\r\n");
      out.write("							<!-- Card body -->\r\n");
      out.write("							<div class=\"card-body d-flex flex-column\"\r\n");
      out.write("								style=\"flex: 1; overflow: hidden; padding: 15px;\">\r\n");
      out.write("								<div\r\n");
      out.write("									class=\"d-flex justify-content-between align-items-center mb-2\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<h5 class=\"card-title\" style=\"font-size: 1.1rem; margin: 0;\">");
      out.print(item.getMenuname());
      out.write("</h5>\r\n");
      out.write("										<p class=\"card-text\" style=\"font-size: 0.9rem; margin: 0;\">");
      out.print(item.getDescription());
      out.write("</p>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"badge bg-light text-dark\"\r\n");
      out.write("										style=\"font-size: 0.875rem;\">\r\n");
      out.write("										");
      out.print(item.getPrice());
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			} else {
			
      out.write("\r\n");
      out.write("			<div class=\"col-12\">\r\n");
      out.write("				<div class=\"row mt-2 justify-content-center align-items-center\">\r\n");
      out.write("					<div class=\"col-md-6 position-relative\">\r\n");
      out.write("						<!-- Image container -->\r\n");
      out.write("						<img src=\"admin/styles/images/notFound.jpg\" alt=\"No Results Found\"\r\n");
      out.write("							class=\"img-fluid w-100\" style=\"height: auto;\">\r\n");
      out.write("\r\n");
      out.write("						<!-- Overlay message -->\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"position-absolute top-50 start-50 translate-middle text-center w-100\">\r\n");
      out.write("							<div class=\"alert alert-info mb-0\" style=\"opacity: 0.85;\"\r\n");
      out.write("								role=\"alert\">No menu items match your search criteria.</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("			");

			ArrayList<Integer> cart = (ArrayList<Integer>) session.getAttribute("cart");
			if (cart != null && cart.size() > 0) { // Show if cart has items
			
      out.write("\r\n");
      out.write("			<a href=\"cart.jsp\" class=\"text-decoration-none\">\r\n");
      out.write("				<div class=\"d-flex justify-content-center\">\r\n");
      out.write("					<div class=\"card floating-cart col-md-8\"\r\n");
      out.write("						style=\"background-color: lightgreen;\">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"card-body d-flex align-items-center justify-content-center\"\r\n");
      out.write("							style=\"height: 70px;\">\r\n");
      out.write("							<!-- Adjust height as needed -->\r\n");
      out.write("							<p class=\"mb-0 text-white\">\r\n");
      out.write("								");
      out.print(cart.size());
      out.write("\r\n");
      out.write("								items added, <span>view in cart</span> <i\r\n");
      out.write("									class=\"fas fa-shopping-basket\"></i>\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<script\r\n");
      out.write("			src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js\"></script>\r\n");
      out.write("		<script\r\n");
      out.write("			src=\"https://stackpath.bootstrapcdn.com/bootstrap/5.0.2/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
