/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-03-07 06:50:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.http.HttpSession;

public final class adminSignUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Admin Sign Up</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Link to the favicon for the website -->\r\n");
      out.write("<link rel=\"icon\" href=\"styles/images/favicon.png\" type=\"image/png\">\r\n");
      out.write("\r\n");
      out.write("<!-- Font Awesome CSS for icons -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap 4.5.2 CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap 5.0.2 CSS with integrity check -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for the admin signup page -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/admin.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	 ");

        session = request.getSession(false);
        if (session == null || session.getAttribute("isLoggedIn") == null) {
            response.sendRedirect(request.getContextPath() + "/index.jsp");
            return;
        }
	
      out.write("\r\n");
      out.write("	<!-- Initialize session variables for tracking signup steps -->\r\n");
      out.write("	");

	session = request.getSession();
	Integer status = (Integer) session.getAttribute("status");
	Integer currentStep = (Integer) session.getAttribute("currentStep");
	String platformKey = (String) session.getAttribute("platformKey");

	// If session variables are not present, set default values
	if (currentStep == null) {
		currentStep = 1;
	}
	if (status == null) {
		status = 0;
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Main container for the admin signup process -->\r\n");
      out.write("	<div class=\"admin py-5\">\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"container d-flex justify-content-start align-items-center my-5\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"card shadow-lg col-12 col-md-6 col-lg-4 col-xl-4 custom-styles\">\r\n");
      out.write("				<div class=\"card-body py-4\">\r\n");
      out.write("					<!-- Process description for each step of the signup -->\r\n");
      out.write("					<div class=\"process-description\">\r\n");
      out.write("						<p class=\"text-danger pb-2\" style=\"font-size: 16px;\">\r\n");
      out.write("							Follow the below processes to Create an Account <i\r\n");
      out.write("								class=\"fas fa-user-plus\" style=\"font-size: 14px;\"></i>\r\n");
      out.write("						</p>\r\n");
      out.write("						<!-- Step 1: Enter the platform key -->\r\n");
      out.write("						<p id=\"step1-text\">\r\n");
      out.write("							<i id=\"step1-tick\" class=\"fas fa-check\"\r\n");
      out.write("								style=\"display: ");
      out.print((currentStep > 1 ? "inline" : "none"));
      out.write("; color: green;\"></i>\r\n");
      out.write("							1. Enter the platform key.\r\n");
      out.write("						</p>\r\n");
      out.write("						<!-- Step 2: Create your admin account -->\r\n");
      out.write("						<p id=\"step2-text\">\r\n");
      out.write("							<i id=\"step2-tick\" class=\"fas fa-check\"\r\n");
      out.write("								style=\"display: ");
      out.print((currentStep > 2 ? "inline" : "none"));
      out.write("; color: green;\"></i>\r\n");
      out.write("							2. Create your admin account with key, password, and\r\n");
      out.write("							confirmation.\r\n");
      out.write("						</p>\r\n");
      out.write("						<!-- Step 3: Provide restaurant name and address -->\r\n");
      out.write("						<p id=\"step3-text\">\r\n");
      out.write("							<i id=\"step3-tick\" class=\"fas fa-check\"\r\n");
      out.write("								style=\"display: ");
      out.print((currentStep > 3 ? "inline" : "none"));
      out.write("; color: green;\"></i>\r\n");
      out.write("							3. Provide restaurant name and address.\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Progress bar to indicate signup progress -->\r\n");
      out.write("					<div class=\"progress mb-4\">\r\n");
      out.write("						<div class=\"progress-bar bg-primary\" id=\"progress-bar\"\r\n");
      out.write("							style=\"width: ");
      out.print((currentStep - 1) * 33.3);
      out.write("%; aria-valuenow=\"\r\n");
      out.write("							");
      out.print((currentStep - 1) * 33.3);
      out.write(" aria-valuemin=\"0\"\r\n");
      out.write("							aria-valuemax=\"100\">");
      out.print(Math.round((currentStep - 1) * 33.3));
      out.write("\r\n");
      out.write("							Complete\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Button container for form navigation -->\r\n");
      out.write("					<div class=\"button-container mb-4 d-flex justify-content-end\">\r\n");
      out.write("						<!-- Start button to initiate the signup process -->\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-success me-auto\"\r\n");
      out.write("							id=\"startForm\">Start</button>\r\n");
      out.write("						<!-- Next button to proceed to the next step -->\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-warning me-2\" id=\"nextButton\">Next</button>\r\n");
      out.write("						<!-- Form submission button to complete the signup process -->\r\n");
      out.write("						<form id=\"signup-form\" action=\"adminSignUp\" method=\"post\"\r\n");
      out.write("							class=\"d-inline\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-success\" id=\"btnSubmitAll\"\r\n");
      out.write("								name=\"step\" value=\"4\">SignUp</button>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Link for existing admins to sign in -->\r\n");
      out.write("					<p class=\"text-center mt-3\" id=\"haveAccount\"\r\n");
      out.write("						style=\"font-size: 14px;\">\r\n");
      out.write("						Already have an account? <a href=\"adminSignIn.jsp\"\r\n");
      out.write("							class=\"text-success\" style=\"color: green; text-decoration: none;\"\r\n");
      out.write("							onmouseover=\"this.style.color='darkgreen'; this.style.textDecoration='underline';\"\r\n");
      out.write("							onmouseout=\"this.style.color='green'; this.style.textDecoration='none';\">Sign\r\n");
      out.write("							In</a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal for entering the platform key (Step 1) -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"platformKeyModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"platformKeyModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"platformKeyModalLabel\">Step 1:\r\n");
      out.write("						Platform Key</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<!-- Form for submitting the platform key -->\r\n");
      out.write("					<form id=\"platformKeyForm\" action=\"adminSignUp\" method=\"post\">\r\n");
      out.write("						<input type=\"hidden\" name=\"step\" value=\"1\">\r\n");
      out.write("						<!-- Input field for the platform key -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"platformKey\" class=\"form-label\">Platform\r\n");
      out.write("								Super Secret Key</label>\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"password\" class=\"form-control\" id=\"platformKey\"\r\n");
      out.write("									name=\"platformKey\" placeholder=\"Enter the key\"\r\n");
      out.write("									value=\"");
      out.print(platformKey != null ? platformKey : "");
      out.write("\" required>\r\n");
      out.write("								<!-- Toggle button to show/hide the platform key -->\r\n");
      out.write("								<div class=\"input-group-append\">\r\n");
      out.write("									<span class=\"input-group-text\" id=\"toggle-platform-key\"\r\n");
      out.write("										data-toggle=\"password\" data-target=\"platformKey\" style=\"cursor: pointer;\"> <i\r\n");
      out.write("										class=\"fas fa-eye\"></i>\r\n");
      out.write("									</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"modal-footer\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-success\"\r\n");
      out.write("								id=\"savePlatformKey\">Save Platform Key</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal for creating the admin account (Step 2) -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"createAccountModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"createAccountModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"createAccountModalLabel\">Step 2:\r\n");
      out.write("						Create Account</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<!-- Form for creating the admin account -->\r\n");
      out.write("					<form id=\"createAccountForm\" action=\"adminSignUp\" method=\"post\">\r\n");
      out.write("						<input type=\"hidden\" name=\"step\" value=\"2\">\r\n");
      out.write("						<!-- Input field for creating the admin key -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"adminKey\" class=\"form-label\">Create Secret\r\n");
      out.write("								Admin Key</label>\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"password\" class=\"form-control\" id=\"adminKey\"\r\n");
      out.write("									name=\"adminkey\" placeholder=\"Enter the admin key\" required>\r\n");
      out.write("								<!-- Toggle button to show/hide the admin key -->\r\n");
      out.write("								<div class=\"input-group-append\">\r\n");
      out.write("									<span class=\"input-group-text\" id=\"toggle-admin-key\"\r\n");
      out.write("										data-toggle=\"password\" data-target=\"adminKey\" style=\"cursor: pointer;\"> <i\r\n");
      out.write("										class=\"fas fa-eye\"></i>\r\n");
      out.write("									</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<small class=\"format-info text-danger\">Format:\r\n");
      out.write("								admin.adminname@restaurantname_address</small>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Input field for creating the admin password -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"password\" class=\"form-label\">Create Password</label>\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"password\" class=\"form-control\" id=\"password\"\r\n");
      out.write("									name=\"password\" placeholder=\"Enter password\" required>\r\n");
      out.write("								<!-- Toggle button to show/hide the admin password -->\r\n");
      out.write("								<div class=\"input-group-append\">\r\n");
      out.write("									<span class=\"input-group-text\" data-toggle=\"password\"\r\n");
      out.write("										data-target=\"password\" style=\"cursor: pointer;\"> <i class=\"fas fa-eye\"></i>\r\n");
      out.write("									</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<small class=\"format-info text-danger\">Password must be\r\n");
      out.write("								at least 8 characters long and include a mix of letters,\r\n");
      out.write("								numbers, and special characters.</small>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- Input field for confirming the admin password -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"confirm-password\" class=\"form-label\">Confirm\r\n");
      out.write("								Password</label>\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"password\" class=\"form-control\"\r\n");
      out.write("									id=\"confirm-password\" name=\"confirmpassword\"\r\n");
      out.write("									placeholder=\"Confirm password\" required>\r\n");
      out.write("								<div class=\"input-group-append\">\r\n");
      out.write("									<span class=\"input-group-text\" data-toggle=\"password\"\r\n");
      out.write("										data-target=\"confirm-password\" style=\"cursor: pointer;\"> <i class=\"fas fa-eye\"></i>\r\n");
      out.write("									</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<small class=\"format-info text-danger\">Password and\r\n");
      out.write("								confirm password should match.</small>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"modal-footer\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-success\" id=\"saveAccount\">Save\r\n");
      out.write("								Account</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal for providing the restaurant details (Step 3) -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"restaurantDetailsModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"restaurantDetailsModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"restaurantDetailsModalLabel\">Step\r\n");
      out.write("						3: Restaurant Details</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<!-- Form for providing the restaurant details -->\r\n");
      out.write("					<form id=\"restaurantDetailsForm\" action=\"adminSignUp\" method=\"post\">\r\n");
      out.write("						<input type=\"hidden\" name=\"step\" value=\"3\">\r\n");
      out.write("						<!-- Input field for the restaurant name -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"restaurantName\" class=\"form-label\">Restaurant\r\n");
      out.write("								Name</label> <input type=\"text\" class=\"form-control\" id=\"restaurantName\"\r\n");
      out.write("								name=\"restaurantname\" placeholder=\"Enter the restaurant name\"\r\n");
      out.write("								required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Input field for the restaurant address -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"restaurantAddress\" class=\"form-label\">Restaurant\r\n");
      out.write("								Address</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("								id=\"restaurantAddress\" name=\"address\"\r\n");
      out.write("								placeholder=\"Enter the restaurant address\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"modal-footer\">\r\n");
      out.write("							<!-- Save button for the restaurant details -->\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-success\"\r\n");
      out.write("								id=\"saveRestaurantDetails\">Save Restaurant Details</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		let currentStep =\r\n");
      out.write("	");
      out.print(currentStep);
      out.write("\r\n");
      out.write("		;\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- Custom JavaScript for handling modal interactions and form submission -->\r\n");
      out.write("	<script type=\"text/javascript\" src=\"styles/password.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"createAdmin.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"admin/styles/password.js\"></script>\r\n");
      out.write("	<!-- jQuery and Bootstrap JS for modals and other features -->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
